#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-only
#-------------------------------------------------------------------#
# Autor       : Jefferson Carneiro <slackjeff@slackjeff.com.br>
# Programa    : flatlight
# DESCRIÇÃO   :
# FlatLight é um gerenciador leve de aplicativos Flatpak via terminal.
# Ele fornece um navegador interativo do Flathub usando fzf, com suporte
# a cache local e um fluxo simples para instalação de aplicativos.
#
# Dependências:
#   - flatpak
#   - fzf
#   - gettext
#
# Recursos:
#   - Gerar/atualizar cache
#   - Instalar aplicativos
#   - Remover aplicativos
#   - Atualizar Flatpaks
#
#-------------------------------------------------------------------#

#----------------------------------#
# Variaveis Globais
#----------------------------------#
export PRG="FlatLight"
export VERSION="1.1-alfa"
export CACHE_FILE="${HOME}/.cache/${PRG}-flathub.cache"
#
# Define o tempo (em segundos) para atualização do cache do Flathub.
export CACHE_TIME="$((24 * 60 * 60))"
#
# Defina as cores aqui!
fRed='\e[31;1m'
fGreen='\e[32;1m'
fYellow='\e[33;1m'
fBlue='\e[34;1m'
fPink='\e[35;1m'
fEnd='\e[m'

#----------------------------------#
# Suporte a (i18n)
#----------------------------------#
export TEXTDOMAIN="${PRG}"
export TEXTDOMAINDIR="${TEXTDOMAINDIR:-./locale}" # Teste local

if [[ -f "/usr/bin/gettext.sh" ]]; then
	. /usr/bin/gettext.sh
else
	eval_gettext() { echo "$1" ;}
fi


#----------------------------------#
# Funções
#----------------------------------#

# Gera/atualiza o CACHE de aplicativos Flatpak do Flathub para uso no seletor fzf.
function update_cache()
{
	echo -e "${fGreen}$(gettext "Gerando o arquivo de cache, Aguarde...")${fEnd}"
	flatpak remote-ls flathub --app --columns=name,application | \
	awk -F '\t' '{printf "%-45s %s\n",$1,$2}' > "$CACHE_FILE"

}

# Função modular para fazer listagem dos apps. É utilizado pelas funções:
# - install_flatpak
# - remove_flatpak
function select_flatpak()
{
    local -n RESULT=$1
    
    # Modo cache por padrão ou installed para instalados no sistema
    local MODE="${2:-cache}"
    
    # Necessário para saber o modo que sera rodado a lista com mapfile.
    local INPUT_CMD
    
    # Estilo do prompt.
    local PROMPT_TEXT="${3:-📦 Apps > }"
    
    # Mensagem que sera exibido para cada tela.
    local TEXT="${4:-$(gettext "Selecione os aplicativos para INSTALAR <TAB seleciona múltiplos>.")}"

	# Qual modo será executado ?
    if [[ "$MODE" == "installed" ]]; then
		# Listagem de apps instalados na máquina do usuário para remoção.
        INPUT_CMD="flatpak list --app --columns=name,application | awk -F '\t' '{printf \"%-45s %s\n\",\$1,\$2}'"
    else
		# Puxa do arquivo de cache do usuario todos apps. (Usuado para instalação)
        INPUT_CMD="cat \"$CACHE_FILE\""
    fi

	# !!! FIXME !!!
	# Precisamos usar o 'eval' para não duplicar esse trecho do mapfile + fzf.
	# Podemos melhorar para evitar o uso do eval...
	    mapfile -t RESULT < <(
        eval "$INPUT_CMD" | fzf \
          --multi \
          --height=80% \
          --layout=reverse \
          --border \
          --margin=1 \
          --padding=1 \
          --prompt="$PROMPT_TEXT" \
          --pointer="➜" \
          --marker="✓" \
          --header="${TEXT}" \
          --info=inline \
          --cycle \
          --bind="ctrl-a:select-all,ctrl-d:deselect-all" | awk '{print $NF}'
    )
}

# INSTALA aplicativos Flatpak selecionados, ignorando pacotes já instalados.
function install_flatpak()
{
	local PACKAGES=()

	select_flatpak PACKAGES

	if [[ ${#PACKAGES[@]} -eq 0 ]]; then
		return 0
	fi

	for PACKAGE in "${PACKAGES[@]}"; do

		if flatpak list --app --columns=application | grep -qx "$PACKAGE"; then
			echo -e "${fGreen}✓ $PACKAGE $(gettext "Já está instalado")${fEnd}"
			sleep 1s
		else
			echo "$(gettext "Instalando") $PACKAGE..."
			flatpak install flathub "$PACKAGE" -y
		fi

	done
}

# REMOVE aplicativos flatpak da máquina do usuário.
function remove_flatpak()
{
	local PACKAGES=() # inicializando

	select_flatpak PACKAGES "installed" "🗑️ $(gettext "Remover") > " "$(gettext "Selecione os aplicativos para REMOVER (TAB marca).")"

	# Algum pacote foi selecionado?
	if [[ ${#PACKAGES[@]} -eq 0 ]]; then
		return 0
	fi

	for PACKAGE in "${PACKAGES[@]}"; do
		if flatpak list --app --columns=application | grep -qx "$PACKAGE"; then
			echo "$(gettext "Removendo") $PACKAGE..."
			flatpak uninstall "$PACKAGE"
		else
			echo -e "${fRed}⚠ $PACKAGE $(gettext "não está instalado")${fEnd}"
			read -n 1 -s -r -p "$(gettext "Pressione qualquer tecla para continuar...")"
		fi
	done
}

# Atualiza todos os aplicativos Flatpak instalados.
function update_flatpak()
{
	echo -e "${fGreen}$(gettext "Atualizando Flatpaks...")${fEnd}"
	flatpak update -y

	read -n 1 -s -r -p "$(gettext "Pressione qualquer tecla para continuar...")"
}

# Verifica se o cache expirou e precisa ser regenerado.
function check_cache_update()
{
	local age

	[[ ! -e "$CACHE_FILE" ]] && return  0

	age=$(( $(date +%s) - $(stat -c %Y "$CACHE_FILE") ))
	if [[ "$age" -gt "$CACHE_TIME" ]]; then
		return 0
	else
		return 1
	fi
}

#----------------------------------#
# Testes
#----------------------------------#

#  Have cache? Or need update? 
if check_cache_update; then
	update_cache
fi

# Fallback para gettext (suporte à internacionalização).
# Caso o gettext não esteja instalado, criamos um fallback.
if ! command -v gettext &>/dev/null; then
    gettext() { printf '%s' "$1"; }
fi

#----------------------------------#
# Inicio
#----------------------------------#

# Salva as opções traduzidas em variáveis para bater certinho com o case
OPT_INSTALL="$(gettext "Instalar")"
OPT_REMOVE="$(gettext "Remover")"
OPT_UPDATE="$(gettext "Atualizar")"
OPT_EXIT="$(gettext "Sair")"

while true; do
	#clear
	#cache_generate
	MENU=$(printf "%s\n%s\n%s\n%s" \
      "$(gettext "Instalar")" \
      "$(gettext "Remover")" \
      "$(gettext "Atualizar")" \
      "$(gettext "Sair")" | \
	fzf \
	  --height=40% \
	  --layout=reverse \
	  --border=rounded \
	  --margin=1 \
	  --padding=1 \
	  --prompt="📦 ${PRG} - v${VERSION} > " \
	  --pointer="➜ " \
	  --header="$(gettext "O que deseja fazer?")" \
	  --info=hidden \
	  --no-multi)
	# Converte para minúsculo
    MENU=${MENU,,}

    case "$MENU" in
        "${OPT_INSTALL,,}") install_flatpak ;;
        "${OPT_REMOVE,,}")  remove_flatpak  ;;
        "${OPT_UPDATE,,}")  update_flatpak ;;
        "${OPT_EXIT,,}")    exit 0 ;;
    esac
done
